appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CDGMi9LHS8BrOSnPzCFgPrJroo/m5aHS7W/GRm5gg0xkh5+ATkZxyX3GRjFR3wbT5FaUvGSwCWoW3FeAJbT5EyUMJvDw18oheqQpN5+1LxMFsIWQe/ywpShhuHbuGmHMLrZUlvrQeMVYzSXpdd3eIhT7j7FcNsjni69pqS9eJhPDo3Yaa2elkMZmsApm0BUXrlso54x4ZIbqeBjBw0nIkbYtId+ACf3FFafqYLZlA/0nNy5r7oKymzTH5it/NyH1lx+gmis0Q7j3NQ5uhXnOL0l/sbVYZfPr4ap3HyoL/654grbMUQAjR0Ct2pxhtMbOs7l8znsU2gB9eAzX596r7SagVU2FaYVDNKMSrBqPFqdv+jRgiPhPGSLMnbnHv6DwiG7U+Xck/6U+xd3Pow/ULMut16AKnNmprtpo4rG/ayMBwQEk9trIqj3v+3/41YU4pjnAFJTvaxQtWHz9GLoPMpftN1kalaLN2k2kjL00iVU91Gqf9b8NkYi54nh5HA6mPY6HTXO4aCUh53qW+4RV7GroRMTC8pByYXjB96y5JBSBlhSeLeMsIzyDC4VFLiu2LsQcvo6JB+QX6nSFl3a104abvrjk9NlNwYdfZzvM75GshiWwhRfpg9dAVVteCDu2i1K9B/HGwpYqxuQu7tm4fsc611gYxTunXreqsSo3BUs=}
conda_forge_output_validation: true
